spring.application.name=AlquilerdeAutos

# ACCESO A LA BASE DE DATOS

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/alquilerAutosbd?useSSL=true
spring.datasource.username=root
spring.datasource.password=AdminRoot2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
